/*
 @name : 锅巴汉化 - Web汉化插件
 @author : 麦子、JAR、小蓝、好阳光的小锅巴、人民當家做主
 @version : V0.6.1 - 2026-5-26
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737
*/

// ============================================================
// 匹配配置
// ============================================================
// ignoreCase: true   忽略大小写(Gold/gold/GOLD都匹配), false=区分大小写
// trimSpaces: true   忽略首尾空格(" gold "匹配"gold"), false=保留空格
//
// 影响范围：
//   ✅ cnItems 精确匹配(字符串值+数组值)
//   ✅ cnItems 分类索引({{分类名}}/{{分类名*}}/{{分类名*|sep|join}})
//   ✅ cnResourceNames 名词翻译
//   ✅ cnPrefix / cnPostfix 前后缀
//   ✅ cnRegReplace / 排除规则 / 模板正则(通过 addIgnoreCaseFlag / cnConfig.ignoreCase 控制)
var cnConfig = {
    ignoreCase: true,
    trimSpaces: true,
};

// ============================================================
// cnCategoriesList — 分类名称注册表（供编辑器工具使用）
// ============================================================
// 分类数据由 cnItems 中的数组值 ["译文", "分类名"] 自动构建。
// 此列表仅声明有哪些分类，以便编辑器提供分类选择/管理功能。
var cnCategoriesList = [
    "resource",
    "item",
];

// ============================================================
// cnItems — 主要翻译词条
// ============================================================
// 用法：
//   "原文": "译文"                         → 精确静态匹配
//   "原文": ["译文", "分类名"]               → 静态匹配 + 自动加入分类
//   "Cost: {{0}}": "消耗：{{0}}"            → 模板匹配 ({{0}} 匹配任意值)
//   "{{resource}}: {{%d}}": "{{resource}}：{{%d}}"  → 分类模板 + 数字验证
//   "{{分类名*}}": 仅在该分类查找，找不到保留原文
//   "{{分类名*|sep|join}}": 分类限定列表解析
//   "{{*}}": 通用列表，逐项递归翻译
//   "{{*|sep|join}}": 自定义分隔符/连接词的列表
// ============================================================
var cnItems = {
    // --- 静态匹配 ---
    "Welcome": "欢迎",
    "Score": "分数",
    "Health Potion": "生命药水",
    "Hello World": "你好世界",

    // --- 分类词条 [译文, 分类名] ---
    "gold": ["金币", "resource"],
    "wood": ["木材", "resource"],
    "stone": ["石头", "resource"],
    "iron": ["铁", "resource"],
    "sword": ["剑", "item"],
    "shield": ["盾牌", "item"],
    "helmet": ["头盔", "item"],

    // --- 模板 ({{0}} / {{1}}) ---
    "Cost: {{0}}": "消耗：{{0}}",
    "Next Improvement: {{0}}": "下次提升：{{0}}",
    "Level {{0}}": "等级{{0}}",
    "+{{0}}/m": "+{{0}}/m",
    "{{0}} x {{1}}": "{{0}} × {{1}}",

    // --- 模板 ({{分类名}} + {{%d}}) ---
    "{{resource}}: {{0}}": "{{resource}}：{{0}}",

    // --- 模板 ({{分类名*}} 仅分类) ---
    "Get {{0}} {{resource*}}": "获得 {{0}} {{resource*}}",

    // --- 模板 ({{分类名*|sep|join}} 分类列表) ---
    "Craft {{item*|,|和}}": "制作{{item*|,|和}}",

    // --- 通用列表 {{*}} / {{*|sep|join}} ---
    "Items: {{*}}": "物品：{{*}}",
    "Mats: {{*|, |、}}": "材料：{{*|, |、}}",

    // --- 数字占位符 {{%d}} ---
    "HP: {{%d}}": "生命值：{{%d}}",
    "DMG: {{%d}}": "伤害：{{%d}}",

    " Prestige ":"声望",
    " Shop ":"商店",
    " Trail ":"行进路径",
    " World ":"世界",
    "Ants":"蚂蚁",
    "Chitin":"几丁质",
    "Colony Game":"蚁群游戏",
    "Dew":"露水",
    "Food":"食物",
    "IdleAnt":"放置蚂蚁",
    "Prestige":"声望",
    "Shop":"商店",
    "Trail":"行进路径",
    "World":"世界",
    " Continue ":"继续",
    " No income while away ":"离线无收益",
    "(0% of cap)":"（上限的0%）",
    "(1% of cap)":"（上限的1%）",
    "Colony Update":"蚁群状态更新",
    "Offline Time":"离线时长",
    "Resources Gained":"获取资源",
    "While You Were Away":"离线期间收益",
    "max 2h":"最多2小时",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],

    "Mythic": "神话",
    "Legendary": "传说",
    "Epic": "史诗",
    "Rare": "稀有",
    "Uncommon": "罕见",
    "Common": "普通",
    "SPD": "速度",
    "ATK": "攻击",
    "ARM": "护甲",
    "Lvl": "等级",
    "Unlock": "解锁",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "—": "—",
    "•": "•",
    "−": "−",
    "×": "×",
    "←": "←",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "设置",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',

    // --- 新增翻译 (策略2: 占位符模板) ---
    "({{0}}) for {{1}}s (Max Stacks": "({{0}}) 持续 {{1}}秒 (最大层数",
    " buff for {{0}}s. (max. {{1}})": " 增益持续 {{0}}秒。(最大 {{1}})",
    "Killing an enemy grants a stacking {{0}}% ": "击杀敌人获得叠加 {{0}}% ",
    "Successfully blocking an attack applys ": "成功格挡攻击施加 ",
    "eal {{0}}% extra": "额外 {{0}}% ",
    "amage) for {{0}}s.": "伤害) 持续 {{0}}秒。",
    "{{0}}% chance to ": "{{0}}% 几率 ",
    " ({{0}}m) ": " ({{0}}分钟) ",
    "Tax Collection ": "征税 ",
    "x{{0}} (+{{1}}%)": "x{{0}} (+{{1}}%)",
    "{{0}} Sockets ": "{{0}} 插槽 ",
    " for {{0}}s.": " 持续 {{0}}秒。",
    // --- 蚁群游戏新增 ---
    " Locked - {{0}} food": " 锁定 - {{0}} 食物",
    " Locked - {{0}} honeydew": " 锁定 - {{0}} 蜜露",
    "{{0}} chitin -> {{1}} honeydew": "{{0}} 几丁质 -> {{1}} 蜜露",
    "{{0}} food -> {{1}} honeydew": "{{0}} 食物 -> {{1}} 蜜露",
    "{{0}} honeydew -> {{1}} food": "{{0}} 蜜露 -> {{1}} 食物",
    "{{0}} food": "{{0}} 食物",
    "{{0}} honeydew": "{{0}} 蜜露",
    "+{{0}} jelly": "+{{0}} 蜂王浆",
    "{{0}} jelly": "{{0}} 蜂王浆",
    "Lv {{0}}/{{1}}": "等级 {{0}}/{{1}}",
    "{{0}} -> {{1}} starting ants": "{{0}} -> {{1}} 初始蚂蚁",
    "{{0}}h -> {{1}}h": "{{0}}小时 -> {{1}}小时",
    "in {{0}}": "{{0}}后",
    "x{{0}} -> x{{1}}": "x{{0}} -> x{{1}}",
    "{{0}}/m": "{{0}}/分钟",
    "{{0}}/min": "{{0}}/分钟",
    "{{0}}s -> {{1}}s": "{{0}}秒 -> {{1}}秒",
    "{{0}} trips -> {{1}} trips": "{{0}} 趟 -> {{1}} 趟",
    "Ants: {{0}}": "蚂蚁：{{0}}",
    "Needs {{0}}": "需要 {{0}}",
    "in {{0}}m {{1}}s": "{{0}}分{{1}}秒后",
    "in {{0}}s": "{{0}}秒后",
    "in {{0}}h {{1}}m": "{{0}}小时{{1}}分后",
    "x{{0}}": "x{{0}}",
    "{{0}}%": "{{0}}%",
    "Need {{0}} food produced this run to prestige ": " 本轮生产 {{0}} 食物才能声望 ",
    "{{0}}s": "{{0}}秒",
    " x{{0}}": " x{{0}}",
    "{{0}}m {{1}}": "{{0}}分 {{1}}",
    "{{0}} trip": "{{0}} 趟",
    "{{0}} trips": "{{0}} 趟",
    "{{0}} sense": "{{0}} 感知",
    "{{0}} carry": "{{0}} 携带",
    "{{0}} legacy": "{{0}} 遗产",
    "(0% of cap)": "（上限的0%）",
    "Classic foragers gather scattered morsels and return the": "经典觅食蚁收集散落的食物碎屑并运回",
    "to the nest.": "蚁巢。",
    "Ants detect food fro": "蚂蚁从更远处",
    "Each ant delivers more food per": "每只蚂蚁每趟运送更多",
    "Workers hesitate for less time during rando": "工蚁在随机移动暂停时",
    "farther away": "更远处",
    "movement pause": "移动暂停",
    "Each delivered morsel fro": "此来源每份运送的",
    "this source is worth more": "食物更有价值",
    "More passive income fro": "更多被动收入来自",
    "retired runs of this colony.": "此蚁群的退役轮次。",

};
// ============================================================
// cnResourceNames — 资源名词翻译（备用，优先级低于 cnItems）
// ============================================================
// 支持 "名词: 数值" 格式的自动翻译（如 "Mana: 500" → "法力：500"）
var cnResourceNames = {
    // --- 蚁群游戏新增 ---
    " Global Shop ": " 全局商店 ",
    "Aphid farmers tend leafy clusters, collect honeydew, and bring it home.": "蚜虫农照料叶片群落，采集蜜露并带回蚁巢。",
    "Canopy Farm": "树冠农场",
    "Classic foragers gather scattered morsels and return them to the nest.": "经典觅食蚁收集散落的食物碎屑并运回蚁巢。",
    "Frontier Guard": "边境守卫",
    "Honeydew": "蜜露",
    "Meadow Nest": "草甸巢穴",
    "Now": "当前",
    "Passive": "被动",
    "Royal Jelly": "蜂王浆",
    "Soldier ants raid hostile dens, fall wounded, and respawn at the nest.": "兵蚁突袭敌对巢穴，受伤后在蚁巢重生。",
    "Close": "关闭",
    "Conversion": "转换",
    "Global Shop": "全局商店",
    "Unlock aphid farmers and honeydew production.": "解锁蚜虫农和蜜露生产。",
    "Unlock soldier ants, enemy dens, wounded respawns, and chitin raids.": "解锁兵蚁、敌穴、受伤重生和几丁质掠夺。",
    "Unlocks": "解锁",
    "World View": "世界视图",
    " Close ": " 关闭 ",
    " Wipe All Data ": " 清除所有数据 ",
    "Danger Zone": "危险区域",
    "Wipes all progress — resources, colonies, upgrades, Royal Jelly. Cannot be undone.": "清除所有进度——资源、蚁群、升级、蜂王浆。不可撤销。",
    " Prestige Colony ": " 声望蚁群 ",
    " Reset this colony and lock in your best production rate as permanent passive income. Earn 1 Royal Jelly per 1,000 food produced this run. ": " 重置此蚁群，将最佳生产率锁定为永久被动收入。本轮每生产 1,000 食物获得 1 蜂王浆。 ",
    "Ant sensing in all colonies.": "所有蚁群的蚂蚁感知范围。",
    "Colony Shop": "蚁群商店",
    "Completed seed hauls add global carry capacity.": "完成的种子搬运增加全局携带容量。",
    "Dense Workforce": "密集劳动力",
    "Food and honeydew income in every colony.": "每个蚁群的食物和蜜露收入。",
    "Keep more measured income while away.": "离线时保留更多计量收入。",
    "Larger colonies multiply carry capacity.": "更大的蚁群倍增携带容量。",
    "More passive income from retired runs of this colony.": "此蚁群退役轮次提供更多被动收入。",
    "Needs 2+ Meadow food sources": "需要 2 个以上草甸食物源",
    "Needs Meadow Trail Length research": "需要草甸路径长度研究",
    "Needs completed seed hauls": "需要完成种子搬运",
    "Needs more than 1 active ant": "需要多于 1 只活跃蚂蚁",
    "Network Logistics": "网络物流",
    "New Passive Rate": "新被动速率",
    "Offline Cap": "离线上限",
    "Offline Efficiency": "离线效率",
    "Persistent Upgrades": "持久升级",
    "Persistent carry capacity for this colony.": "此蚁群的持久携带容量。",
    "Persistent sensing range for this colony.": "此蚁群的持久感知范围。",
    "Produced This Run": "本轮生产量",
    "Retire this run": "退役本轮",
    "Royal Brood": "皇家孵化",
    "Royal Chamber": "皇家密室",
    "Royal Founding": "皇家创立",
    "Royal Legacy": "皇家遗产",
    "Royal Scent": "皇家气味",
    "Seed Infrastructure": "种子基建",
    "Seed hauls 0": "种子搬运 0",
    "Shared Pheromones": "共享信息素",
    "Source Specialization": "资源专精",
    "Start each new run with one extra ant per level.": "每级开始新轮次时额外获得一只蚂蚁。",
    "Store progress for more time while away.": "离线时更长时间存储进度。",
    "Trail Logistics": "路径物流",
    "Trail length research multiplies meadow food output.": "路径长度研究倍增草甸食物产出。",
    "Unlocked meadow sources boost each other.": "已解锁的草甸资源互相增益。",
    "persists after reset": "重置后保留",
    "spent on reset": "重置时消耗",
    " Crumbs": " 碎屑",
    " Fruit": " 水果",
    " Protein": " 蛋白质",
    " Seeds": " 种子",
    " Sugar": " 糖",
    "Affordable first": "最便宜优先",
    "Best payback": "最佳回报",
    "Buy": "购买",
    "Cheapest first": "最便宜优先",
    "Common baseline carry.": "通用基础携带量。",
    "Crumbs": "碎屑",
    "Crumbs Upgrades": "碎屑升级",
    "Default order": "默认顺序",
    "Each delivered morsel from this source is worth more": "此来源每份运送的食物更有价值",
    "Food morsels appear more frequently": "食物碎屑出现更频繁",
    "Max Morsels": "最大碎屑数",
    "More food morsels exist at once": "同时存在更多食物碎屑",
    "Spawn Rate": "生成速率",
    "Type": "类型",
    "Yield Bonus": "产量加成",
    "max": "最大",
    "Adds one worker to this colony.": "为此蚁群增加一只工蚁。",
    "Ant Speed": "蚂蚁速度",
    "Ants detect food from farther away": "蚂蚁从更远处探测食物",
    "Carry Capacity": "携带容量",
    "Each ant delivers more food per trip": "每只蚂蚁每趟运送更多食物",
    "Extend the pheromone trail ants can follow": "延长蚂蚁可追踪的信息素路径",
    "Foragers move faster between nest and food": "觅食蚁在蚁巢和食物间移动更快",
    "Gait Discipline": "步态纪律",
    "Labor": "劳动力",
    "Research": "研究",
    "Rest Recovery": "休息恢复",
    "Sense Radius": "感知半径",
    "Spawn ant": "生成蚂蚁",
    "Trail Length": "路径长度",
    "Worker Endurance": "工蚁耐力",
    "Workers complete more trips before they need to rest": "工蚁在需要休息前完成更多趟搬运",
    "Workers hesitate for less time during random movement pauses": "工蚁在随机移动暂停时犹豫时间更短",
    "Workers spend less time resting after hauling their limit": "工蚁搬运达上限后休息时间更短",
    "Fruit Locked": "水果已锁定",
    "Unlock to expand this colony's production area.": "解锁以扩展此蚁群的生产区域。",
    " Skip [Space] ": " 跳过 [空格] ",
    " Welcome Back! ": " 欢迎回来！ ",
    "Combat Rewar": "战斗奖励",
    "Foes Slain": "敌人击杀",
    "Victory": "胜利",
    "venturer": "冒险者",
    "Continue": "继续",
    "Han": "韩",
    " Ring Mail ": " 环甲 ",
    "Xar": "扎尔",
    "assh The Necromancer has appeare": "死灵法师拉什已出现",
    "assh has move": "拉什已移动",
    "Rusty Paul": "生锈的保尔",
    " Iron Lantern ": " 铁灯笼 ",
    " Heavy Bracers ": " 重型护腕 ",
    "Bat": "蝙蝠",
    "Leather Boots": "皮靴",
    "Archery Bracers": "射术护腕",
    "Combat": "战斗",
    "Mercenary's Creed": "佣兵信条",
    "Sellsword": "雇佣剑士",
    "Veteran": "老兵",
    "rills": "战栗",
    "Battle Har": "战斗坚",
    "Cheap Shot": "卑鄙一击",
    "ened": "已强化",
    "Opportunist": "机会主义者",
    "Weapon Specialist": "武器专家",
    " to the attacker.": " 给攻击者。",
    "heal you.": "治疗你。",
    "Devout Soul": "虔诚之魂",
    "y Frame": "躯体",
    "Captain": "队长",
    "+1 Energy": "+1 能量",
    "A massive swing": "一次猛烈的挥击",
    "Giant Sweep": "巨力横扫",
    "Combat Proficiency": "战斗熟练",
    "Confusion": "混乱",
    "Gouge": "凿击",
    "Mercenary Fury": "佣兵之怒",
    "Target a weak point.": "瞄准弱点。",
    "Veteran Strikes": "老兵连击",
    "+10% Attack Speed": "+10% 攻击速度",
    "+10% Weapon": "+10% 武器",
    "+5% Multistrike Chance": "+5% 多重打击几率",
    "Apprentice Official": "见习官员",
    "Public Service": "公共服务",
    "Tax Collection": "征税",
    "uty!": "职责！",
    "Visit the local villages to collect the Royal Share. A basic but necessary": "走访当地村庄，收取皇家份额。一项基本但必要的",
    "source.": "来源。",
    "Tratem has arrive": "特拉特姆已抵达",
    "Felt Hat": "毡帽",
    "Leather Legs": "皮护腿",
    "Longbow": "长弓",
    "Rough Ring of the Stu": "学徒粗制戒指",
    "en Circlet": "头环",
    "of the Stu": "学徒",
    " Longbow ": " 长弓 ",
    "Cross": "十字弓",
    "Gemme": "宝石",
    "Ruby": "红宝石",
    "\"A sharp, re": "\"一种锋利、",
    "gemstone. Fits in Re": "宝石。可镶入红",
    "or Prismatic sockets.\"": "或棱彩插槽。\"",
    "Bought Chippe": "购买碎裂",
    "Ruby for 1597": "红宝石 花费 1597",
    " Socket Forging ": " 插槽锻造 ",
    "The Focal Vessel": "聚焦容器",
    "The voi": "虚空",
    "epths.": "深处。",
    " Socketing a gem into a ": " 将宝石镶入 ",
    "Color Mismatch": "颜色不匹配",
    "Gemstones": "宝石",
    "Socket Forging": "插槽锻造",
    "Socketing": "镶孔",
    "sockets to your gear to insert powerful gemstones.": "为装备增加插槽以镶入强力宝石。",
    "down.": "下。",
    "mismatched": "不匹配",
    "into equipment.": "到装备中。",
    " Select Vessel": " 选择容器",
    "Inscribe": "铭刻",
    "Sockets": "插槽",
    "Battle Axe": "战斧",
    "Heavy Bracers": "重型护腕",
    "Garviwg's items.": "加维格的物品。",
    "Griffin Shield": "狮鹫盾",
    "Refreshe": "已刷新",
    "Silver Chain": "银链甲",
    "Steel Tassets": "钢制裙甲",
    "Stock Refreshed": "库存已刷新",
    "The anvil's been hot all": "铁砧整日炙热",
    "ay. Look at this!": "。看看这个！",
    " Silver Chain ": " 银链甲 ",
    "Griffin Shiel": "狮鹫盾",
    " Steel Tassets ": " 钢制裙甲 ",
    " Item Tempering ": " 物品淬炼 ",
    " Select an item from your inventory to begin tempering ": " 从背包中选择一件物品开始淬炼 ",
    "Select Item": "选择物品",
    " The item will be ": " 物品将会被 ",
    "Chance to fail": "失败几率",
    "Increasing an item's level improves its capacity for magic, potentially empowering existing affixes or manifesting new ones.": "提升物品等级可增强其魔法容量，可能强化现有词缀或显现新词缀。",
    "Temper Gra": "淬炼等",
    "cost.": "消耗。",
    "e fails.": "失败。",
    "e of the item. Items can be tempered": "物品。物品可淬炼",
    "Select Item to Temper ": " 选择要淬炼的物品 ",
    "Rusty Sabatons of the Voyager": "航海者生锈铁靴",
    "Star Shatterer": "碎星者",
    "Titan's Maul": "泰坦重锤",
    " Rusty Sabatons ": " 生锈铁靴 ",
    "of the Voyager": "航海者",
    " Star Shatterer ": " 碎星者 ",
    "\"A weapon that resonates with the en": "\"一件与万物",
    "of all things.\"": "共鸣的武器。\"",
    " Titan's Maul ": " 泰坦重锤 ",
    "s for Garviwg's": "加维格",
    "Barbuta Helm": "巴布塔头盔",
    "Bla": "布莱",
    "Frost-Shar": "冰霜",
    "Hammer": "锤",
    "Nimble Grimoire of Steel": "钢铁灵巧魔典",
    "Protective Templar Helm": "防护圣殿头盔",
    "Quiver of Infinite Skies": "无尽苍穹箭袋",
    "Steel Sabatons": "钢制铁靴",
    "Strong Steel Cuirass of Regeneration": "再生强钢胸甲",
    " Steel Cuirass ": " 钢制胸甲 ",
    " Templar Helm ": " 圣殿头盔 ",
    "Protective": "防护",
    "of Regeneration": "再生",
    " Grimoire ": " 魔典 ",
    "of Steel": "钢铁",
    " Steel Sabatons ": " 钢制铁靴 ",
    " Barbuta Helm ": " 巴布塔头盔 ",
    " Quiver of Infinite Skies ": " 无尽苍穹箭袋 ",
    "\"The steel is unnaturally col": "\"这钢铁异常冰",
    "to the touch.\"": "凉。\"",
    "Iron Bucket Helm": "铁桶头盔",
    "Knight Boots": "骑士靴",
    "Morningstar of Speed": "迅捷流星锤",
    "Tool Belt": "工具腰带",
    " Iron Bucket Helm ": " 铁桶头盔 ",
    " Knight Boots ": " 骑士靴 ",
    "Jagged": "锯齿",
    "of Speed": "迅捷",
    "Chainmail Legs": "锁甲护腿",
    "Cleaver": "剁肉刀",
    "Hatchet": "手斧",
    "Kite Shield": "鸢盾",
    "Plate": "板甲",
    "Polishe": "抛光",
    "Silver Ring": "银戒指",
    "Kite Shiel": "鸢盾",
    " Cleaver ": " 剁肉刀 ",
    " Hatchet ": " 手斧 ",
    "Cracke": "碎裂",
    "Heavy Belt": "重型腰带",
    "Pot Helm": "锅盔",
    "Royal Paul": "皇家保尔",
    "War Pike": "战矛",
    "en Rapier": "细剑",
    "en's Leggings": "护腿",
    " War Pike ": " 战矛 ",
    // --- 蚁群游戏第3批 ---
    "Clear Trail": "清除路径",
    "Draw Trail": "绘制路径",
    "2+ Meadow food source": "2个以上草甸食物源",
    "Meadow Trail Length research": "草甸路径长度研究",
    "Network Logistic": "网络物流",
    "Persistent Upgrade": "持久升级",
    "Royal": "皇家",
    "Shared Pheromone": "共享信息素",
    "Trail Logistic": "路径物流",
    "completed seed haul": "已完成种子搬运",
    "more than 1 active ant": "多于1只活跃蚂蚁",
    "Crumb": "碎屑",
    "Crumbs Upgrade": "碎屑升级",
    "Max Morsel": "最大碎屑",
    "Seed": "种子",
    "Yield Bonu": "产量加成",
    "Foragers move faster between nest and": "觅食蚁在蚁巢和食物间移动更快",
    "Sense Radiu": "感知半径",
    "Workers hesitate for less time during random movement pause": "工蚁在随机移动暂停时犹豫时间更短",
};
// cnRegReplace — 正则替换（备用，优先级低于精确匹配但高于模板/分类）
var cnRegReplace = new Map([
    // 经验速率模式: "Xxx Exp: 值/s"
    [/^(.+?) (?:Exp|XP|Experience): ([\d\.]+)\/s$/, '$1经验：$2/s'],
]);
// 前缀/后缀提取（备用）
var cnPrefix = {};
var cnPostfix = {};
// 排除规则（备用）
var cnExcludeWhole = [];
var cnExcludePostfix = [];
